{{- if .Values.valkey.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oklavier-valkey
  namespace: {{ include "oklavier.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oklavier-valkey
  template:
    metadata:
      labels:
        app: oklavier-valkey
    spec:
      containers:
        - name: valkey
          image: "{{ .Values.valkey.image.repository }}:{{ .Values.valkey.image.tag }}"
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.valkey.resources | nindent 12 }}
          command: ["valkey-server", "--save", "", "--appendonly", "no", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru"]
---
apiVersion: v1
kind: Service
metadata:
  name: oklavier-valkey
  namespace: {{ include "oklavier.namespace" . }}
spec:
  selector:
    app: oklavier-valkey
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
