{{- if .Values.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: oklavier-agent
  namespace: {{ include "oklavier-agent.namespace" . }}
  labels:
    {{- include "oklavier-agent.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: oklavier-agent
{{- end }}
