apiVersion: v1
kind: Secret
metadata:
  name: oklavier-agent
  namespace: {{ include "oklavier-agent.namespace" . }}
type: Opaque
stringData:
  token: {{ required "agent.token is required" .Values.agent.token | quote }}
